name: jpc First Workflow
on: 
  push:
    branches:
      - main
  workflow_dispatch: 
  
jobs:
  Job_01:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from my very first GitHub Workflow"

      - name: CheckOut
        uses: actions/checkout@v6.0.2

      - name: ListFiles
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
  Job_02:
    runs-on: ubuntu-latest
    needs: Job_01
    steps:
      - run: "echo Job: ${{ github.job }}"
    #      echo "...and now we are COMPLETED"
      
          
      
